language: ruby
rvm:
  - 2.2.2

cache:
  bundler: true
  directories:
    - node_modules

install:
  - bundle install
  - npm install

script:
  - npm run dev
  - npm test
##### TODO enable production deployment
#  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then npm run prod; fi
