title: Jean Flanagan
tagline: "science education specialist, writer, editor"
author:
  name: Jean Flanagan
  email: jeancflanagan@gmail.com
url: http://jeancflanagan.com
subscribe_url: http://jeancflanagan.com/subscribe
image_url: https://s3.amazonaws.com/static.jeancflanagan.com/images
photoset_url: https://s3.amazonaws.com/static.jeancflanagan.com/images/photosets
siteimage_url: https://s3.amazonaws.com/static.jeancflanagan.com/images/site
scripts_url: https://s3.amazonaws.com/static.jeancflanagan.com/scripts

pygments: true
layouts: ./_layouts
plugins: ./_plugins
exclude: ['Rakefile', 's3_website.yml']

permalink: /:year/:title/
markdown: kramdown