title: Jean Flanagan
tagline: "science education specialist, writer, editor"
author:
  name: Jean Flanagan
  email: jeancflanagan@gmail.com
url: http://jeancflanagan.com
image_url: https://s3.amazonaws.com/temporary.static.jeancflanagan
photoset_url: https://s3.amazonaws.com/temporary.static.jeancflanagan/photosets

pygments: true
layouts: ./_layouts
plugins: ./_plugins
exclude: ['Rakefile', 's3_website.yml']

permalink: /:year/:title/
markdown: kramdown