###### !CONFIG replace these defaults
title: Jekyll Basis
author:
  name: First Last
  email: 'email@example.com'
  twitter: '@twitterhandle'
description: ''

###### !CONFIG choose content attribution license
license:
  short: 'CC BY-NC 4.0'
  long: 'Creative Commons Attribution-NonCommercial 4.0 International'

# Content

## Referenced URLs (internal and external links for inline use)
link:
###### !CONFIG choose content attribution license
  attribution: http://creativecommons.org/licenses/by-nc/4.0/
###### !CONFIG Add other feeds as needed.
  subscribe:
    full: /full.xml

## Collections

collections:
  patterns:
    output: true
    permalink: patterns/:path/

# Site configuration

## Gems configuration
gems:
  - sass

## Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

###### !CONFIG choose a URL structure for posts
## Permalink configuration
permalink: /:year/:month/:title/

## Sass configuration
sass:
  sass_dir: resources/scss
  style: compressed

## Project configuration
include:
  - _feeds
  - _pages

exclude:
  - _config
  - Gemfile*
  - node_modules
  - package.json
  - resources/js

## Collections

collections:
  patterns:
    output: true
    permalink: patterns/:path/

###### !CONFIG add a domain and URL.
## Configuration URLs
domain: 'example.com'
url: 'http://example.com'
patterns_url: /patterns
image_url: /images
icon_url: /icons
resources_url: /resources

###### !CONFIG https://www.google.com/webmasters/verification
## Google site verification
google_verification: ''
