title: Jean Flanagan
author:
  name: Jean Flanagan
  email: jeancflanagan@gmail.com
  twitter: '@jeancflanagan'
  tagline: 'science education specialist, writer, editor'
description: ''

license:
  short: 'CC BY-NC 4.0'
  long: 'Creative Commons Attribution-NonCommercial 4.0 International'

# Content

## Referenced URLs (internal and external links for inline use)
link:
  attribution: http://creativecommons.org/licenses/by-nc/4.0/
###### TODO Add other feeds as needed.
  subscribe:
    full: /full.xml

# Site configuration

##Gems
gems:
  - sass
  - jekyll/imgix

## Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

## Permalink configuration
permalink: /:year/:title/

## Collections
collections:
  patterns:
    output: false
  patterns-categories:
    output: true
    permalink: patterns/:path/

defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: patterns-categories
    values:
      layout: pattern
      category: patterns

## Sass configuration
sass:
  sass_dir: _source/scss
  style: compressed

## Imgix configuration
imgix:
  source: jeancflanagan.imgix.net

## Project configuration
include:
  - _pages

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - .gitignore

## Configuration URLs
domain: jeancflanagan.com
url: http://jeancflanagan.com
patterns_url: /patterns
image_url: /images
icon_url: /icons
resources_url: /resources
