title: Jean Flanagan
author:
  name: Jean Flanagan
  email: jeancflanagan@gmail.com
  twitter: '@jeancflanagan'
  tagline: 'science education & communication specialist'
  portrait: 2017-04-01-pro-portrait.jpg
description: 'Professional website and portfolio for Jean Flanagan, a science education specialist.'

license:
  short: 'CC BY-NC 4.0'
  long: 'Creative Commons Attribution-NonCommercial 4.0 International'
  description: |+
    All content published exclusively on this website is licensed [Creative Commons Attribution NonCommercial 4.0 License](http://creativecommons.org/licenses/by-nc/4.0/) by Jean Flanagan. Content that was originally published elsewhere (whether archived here in full or represented by a snippet) is subject to the copyright specified by those publishers.

# Content

## Referenced URLs (internal and external links for inline use)
link:
  attribution: http://creativecommons.org/licenses/by-nc/4.0/
  twitter: https://twitter.com/jeancflanagan
  linkedin: https://www.linkedin.com/in/jeancflanagan
  source: https://github.com/jeancflanagan/jeancflanagan
  subscribe:
    full: /subscribe/full.xml
    writing: /subscribe/writing.xml
    photo: /subscribe/photos.xml

# Site configuration

## Gems
gems:
  - sass
  - jekyll/imgix
  - jekyll-archives

## Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

## Permalink configuration
permalink: /:year/:title/

## Collections
collections:
  patterns:
    output: false
  patterns-categories:
    output: true
    permalink: patterns/:path/
  photos:
    output: false

defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: patterns-categories
    values:
      layout: pattern
      category: patterns

## Jekyll Archives configuration
jekyll-archives:
  enabled:
    - year
    - categories
  layouts:
    year: archive
    category: archive
  permalinks:
    year: '/:year/'
    category: '/archive/:name/'

## Sass configuration
sass:
  sass_dir: _source/scss
  style: compressed

## Imgix configuration
imgix:
  source: jeancflanagan.imgix.net

## Project configuration
include:
  - _feeds
  - _pages

exclude:
  - Gemfile*
  - .gitignore
  - node_modules
  - package.json

## Configuration URLs
domain: jeancflanagan.com
url: http://jeancflanagan.com
patterns_url: /patterns
image_url: /images
icon_url: /icons
resources_url: /resources

## srcset implementation
sizes: '(min-width: 62.5em) 960px, 100vw'
srcset:
  - 480
  - 640
  - 720
  - 960
  - 1280
  - 1440
